### ISSUE TITLE
Not working with Epson WF-2630

### ISSUE THREAD

**Issue by phampyk** [kn100/telescan#10]
Error output
`{"level":"warn","ts":1683996630.5097356,"caller":"tg/tg.go:241","msg":"There was an error while dealing with a message","user":"Phampyk","message":"🖨 Scan first page","error":"http://EPSONWF-2630/eSCL/ScanJobs: unexpected HTTP status: got 409 Conflict (), want 201","friendly_error":"Telescan couldn't use this scanner"}`

**Comment by kn100** [comment]
Hey! Thanks for the error report. I think I know what's wrong, and it's to do with your scanner having automatic document feeding capability. I'm unsure of how to make THAT work properly, as I don't own a scanner with this capability, but I'll look into it.

**Comment by phampyk** [comment]
In case it helps I currently run [scansrvjs](https://github.com/sbs20/scanservjs) successfully with this same scanner. And I'm willing to test anything you might think work. Just let me know

**Comment by kn100** [comment]
https://github.com/kn100/telescan/pull/11 - would you be willing to test this PR for me? I've provided prebuilt binaries but you can also just pull the repo down and build it yourself if you prefer. Example command to run it can be found in the readme.

**Comment by kn100** [comment]
Potentially fixed by https://github.com/kn100/telescan/releases/tag/v0.1.7 - could you test?

**Comment by phampyk** [comment]
Sorry for such a late reply.
When trying the flatbed I've got 
```
caller=tg/tg.go:241 error=scanner feeder contains no documents: status "ScannerAdfEmpty", want "ScannerAdfLoaded" friendly_error=Telescan couldn't use this scanner level=warn message=🖨 Scan first page msg=There was an error while dealing with a message ts=1684200909.0926485 user=Phampyk
```

when trying the top feeder (used for photocopy) 
```
caller=tg/tg.go:241error=this scanner doesn't support duplex modefriendly_error=Telescan couldn't use this scanner level=warnmessage=🖨 Scan first page msg=There was an error while dealing with a message ts=1684200965.6275744 user=Phampyk
```

Not sure why it says is empty when it's not :/ let me know if there's something else I can show you, like a debug log or something.

**Comment by kn100** [comment]
That's really helpful, thanks. Annoyingly it seems like we must select between ADF and flatbed for scanners that support both.

**Comment by kn100** [comment]
I just pushed another update which might let you use your scanner via the ADF. If you're interested, feel free to give it a try and reopen the issue if it still doesn't work at all!
