### ISSUE TITLE
Figure out how the heck we can make automatic document feeder style scanners work

### ISSUE THREAD

**Issue by kn100** [kn100/telescan#14]
I have no idea how this code currently works with ADF style scanners. I'm imagining it just sucks in one sheet of paper at a time currently, which kind of sucks. It would be nice if instead it would use the ADF capability properly, but I do not have an ADF scanner to test with. Until I find one someone has discarded on the side of the street, this issue is open to anyone with an ADF style scanner.

**Comment by stnokott** [comment]
It's affected by the `Duplex` field in `airscan.ScanSettings`.
Having that to false will suck each sheet in one by one, scanning only the front for each sheet.
Having it to true will suck each sheet in one by one, but scanning both pages in sequence.
This is at least how it works with my Epson WF-7830.

**Comment by stnokott** [comment]
Can confirm that 602dc89a84ebae45b1883809d0d1a4c3465242ac performs duplex scanning (which is the default when using the `airscan.GrayscaleA4ADF` preset) https://github.com/kn100/telescan/blob/602dc89a84ebae45b1883809d0d1a4c3465242ac/scanner/scanner.go#L106

**Comment by kn100** [comment]
@stnokott Great news! That's at least one adf scanner. I'd love for Telescan to properly support ADF though so you don't have to sit there clicking "scan" over and over again.

**Comment by JMyrng** [comment]
I've tested a Brother MFC-L2710DN and got the following results:

Paper on flatbad: `msg=There was an error while dealing with a message user=jonas_m error=scanner feeder contains no documents: status "ScannerAdfEmpty", want "ScannerAdfLoaded"`

Paper in ADF: `msg=There was an error while dealing with a message user=jonas_m error=this scanner doesn't support duplex mode`

I'm using [v0.1.7](https://github.com/kn100/telescan/releases/tag/v0.1.7 )

Anything I can help with?

**Comment by kn100** [comment]
@JMyrng Thanks for testing. I've not got an ADF style scanner to test with unfortunately, so I really am stabbing in the dark here. I just pushed a change (v0.1.8) which may resolve this for you. Are you able to test that? I'd also really appreciate the following:

1. Add DEBUG="true" to your environment variables where you're running this.
2. Start a scan. You should see a log line `Scanner Capabilities` - which will output a bunch of information about what your scanner is capable of. Feel free to scrub any identifying information from this - but I'd love to see the output of this log line. It may help.

**Comment by JMyrng** [comment]
> 2\. Scanner Capabilities

```json
{
    "capabilities": {
        "Adf": {
            "AdfOptions": {
                "AdfOption":"DetectPaperLoaded"
            },
            "AdfSimplexInputCaps":{
                "MaxHeight":4200,
                "MaxOpticalXResolution":2400,
                "MaxOpticalYResolution":2400,
                "MaxPhysicalHeight":4200,
                "MaxPhysicalWidth":2550,
                "MaxScanRegions":true,
                "MaxWidth":2550,
                "MinHeight":64,
                "MinWidth":64,
                "SettingProfiles":{
                    "SettingProfile":{
                        "CcdChannels":{
                            "CcdChannel":["Red","Green","Blue","NTSC","GrayCcd","GrayCcdEmulated"]
                        },
                        "ColorModes":{
                            "ColorMode":["BlackAndWhite1","Grayscale8","RGB24"]
                        },
                        "ColorSpaces":{
                            "ColorSpace":"sRGB"
                        },
                        "ContentTypes":{
                            "ContentType":null
                        },
                        "DocumentFormats":{
                            "DocumentFormat":["application/pdf","image/jpeg"],
                            "DocumentFormatExt":["application/pdf","image/jpeg"]
                        },
                        "SupportedResolutions":{
                            "DiscreteResolutions":{
                                "DiscreteResolution":{
                                    "XResolution":600,
                                    "YResolution":600
                                }
                            }
                        }
                    }
                },
                "SupportedIntents":{
                    "Intent":["Document","TextAndGraphic","Photo","Preview"]
                }
            },
            "AdfDuplexInputCaps":null,
            "FeederCapacity":20,
            "Justification":{
                "XImagePosition":"",
                "YImagePosition":""
            }
        },
        "AdminURI":"http://BRNB42200B373D8/net/net/airprint.html",
        "Certifications":{"Name":"","Version":0},
        "IconURI":"http://BRNB42200B373D8/icons/device-icons-128.png",
        "MakeAndModel":"Brother MFC-L2710DN series",
        "Manufacturer":"Brother",
        "Platen":{
            "PlatenInputCaps":{
                "MaxHeight":3507,
                "MaxOpticalXResolution":2400,
                "MaxOpticalYResolution":2400,
                "MaxPhysicalHeight":3507,
                "MaxPhysicalWidth":2550,
                "MaxScanRegions":true,
                "MaxWidth":2550,
                "MinHeight":64,
                "MinWidth":64,
                "SettingProfiles":{
                    "SettingProfile":{
                        "CcdChannels":{
                            "CcdChannel":["Red","Green","Blue","NTSC","GrayCcd","GrayCcdEmulated"]
                        },
                        "ColorModes":{
                            "ColorMode":["BlackAndWhite1","Grayscale8","RGB24"]
                        },
                        "ColorSpaces":{
                            "ColorSpace":"sRGB"
                        },
                        "ContentTypes":{
                            "ContentType":null
                        },
                        "DocumentFormats":{
                            "DocumentFormat":["application/pdf","image/jpeg"],
                            "DocumentFormatExt":["application/pdf","image/jpeg"]
                        },
                        "SupportedResolutions":{
                            "DiscreteResolutions":{
                                "DiscreteResolution":{
                                    "XResolution":600,"YResolution":600
                                }
                            }
                        }
                    }
                },
                "SupportedIntents":{
                    "Intent":["Document","TextAndGraphic","Photo","Preview"]
                }
            }
        },
        "SerialNumber":"E78290L2N977039",
        "SharpenSupport":{
            "Max":0,
            "Min":false,
            "Normal":0,
            "Step":false
        },
        "UUID":"e3248000-80ce-11db-8000-b42200b373d8",
        "Version":2.63
    }
}
```

It is working now! `ADF Duplex is not available on selected scanner, so using simplex.`

Would be nice if telescan could detect, if ADF is loaded and otherwise use the flatbad scanner.  Or manually change to the flatbad scanner through telegram. 

Really nice work so far!

**Comment by kn100** [comment]
Amazing news! As soon as I source an ADF scanner, I'll build exactly that!

**Comment by JMyrng** [comment]
> It is working now!

Unfortunately, when scanning via ADF, only the first page is saved, even though both pages have been scanned.

**Comment by kn100** [comment]
That's not great. If anyone knows Go and has an ADF scanner to fiddle with, I'm more than open to a PR :)

**Comment by kn100** [comment]
I managed to get my hands on an ADF Simplex scanner, so have added support for that, which seems to work. Let me know how you get on and feel free to re-open this issue.
